/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Register a new user account.
         *
         *     Args:
         *         request (SignupRequest): User registration details including email, password, and name.
         *         db (Session): Database session.
         *
         *     Returns:
         *         SignupUserResponse: Created user information.
         *
         *     Raises:
         *         HTTPException: If email is already registered.
         */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/request-signup-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Signup Token
         * @description Request a new signup verification token.
         *
         *     Args:
         *         payload (RequestSignupTokenRequest): Request containing the user's email.
         *         db (Session): Database session.
         *
         *     Returns:
         *         RequestSignupTokenResponse: New signup verification token.
         */
        post: operations["request_signup_token_api_v1_auth_request_signup_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Signup
         * @description Verify user's email using the signup verification code.
         *
         *     Args:
         *         payload (VerifyEmailRequest): JWT token containing the verification code.
         *         auth_service (AuthService): Authentication service.
         *
         *     Returns:
         *         CommentResponse: Confirmation message about successful verification.
         *
         *     Raises:
         *         HTTPException: If verification code is invalid.
         */
        post: operations["verify_signup_api_v1_auth_verify_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/request-login-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Login Token
         * @description Request a new login verification token.
         *
         *     Args:
         *         payload (RequestLoginTokenRequest): Request containing the user's email and password.
         *         db (Session): Database session.
         *
         *     Returns:
         *         RequestLoginTokenResponse: New login verification token.
         */
        post: operations["request_login_token_api_v1_auth_request_login_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Login
         * @description Verify user's email using the login verification code.
         *
         *     Args:
         *         payload (VerifyLoginRequest): JWT token containing the verification code.
         *         auth_service (AuthService): Authentication service.
         *
         *     Returns:
         *         VerifyLoginResponse: Response containing access token and verification status.
         *
         *     Raises:
         *         HTTPException: If verification code is invalid.
         */
        post: operations["verify_login_api_v1_auth_verify_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout user and clear cookies.
         *
         *     Args:
         *         auth_service (AuthServiceDep): Authentication service.
         *
         *     Returns:
         *         JSONResponse: JSON response with cookies cleared.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Refresh user's access token.
         *
         *     Args:
         *         refresh_token (ValidRefreshTokenDep): Refresh token.
         *
         *     Returns:
         *         JSONResponse: JSON response containing new access token.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Login
         * @description Initiate Google OAuth authentication flow.
         *
         *     Args:
         *         request (Request): FastAPI request object.
         *
         *     Returns:
         *         RedirectResponse: Redirect to Google OAuth consent screen.
         */
        get: operations["google_login_api_v1_auth_google_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Auth
         * @description Handle Google OAuth callback and create user session.
         *
         *     Args:
         *         request (Request): FastAPI request object containing OAuth callback data.
         *         db (Session): Database session.
         *
         *     Returns:
         *         RedirectResponse: Redirect to frontend with access token.
         *
         *     Raises:
         *         HTTPException: If Google authentication fails.
         */
        get: operations["google_auth_api_v1_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Handles password reset requests.
         *
         *     args:
         *         request (ForgotPasswordRequest): Request containing the user's email.
         *
         *     Returns:
         *         dict: Confirmation message about password reset email.
         */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-reset-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Reset Token
         * @description Verify the validity of a password reset token.
         *
         *     Args:
         *         request (VerifyResetTokenRequest): Request containing the reset token.
         *         auth_service (AuthService): Authentication service.
         *     Returns:
         *         VerifyResetTokenResponse: Response indicating if the token is valid.
         */
        post: operations["verify_reset_token_api_v1_auth_verify_reset_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Reset user's password using a valid reset token.
         *
         *     Args:
         *         request (ResetPasswordRequest): Request containing the reset token and new password.
         *         auth_service (AuthService): Authentication service.
         *     Returns:
         *         dict: Confirmation message about successful password reset.
         */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/check-email-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Email Status
         * @description Check if the email is verified.
         *
         *     Args:
         *         payload (CheckEmailStatusRequest): Request containing the user's email.
         *         auth_service (AuthService): Authentication service.
         *     Returns:
         *         CheckEmailStatusResponse: Response indicating if the email is verified.
         */
        post: operations["check_email_status_api_v1_auth_check_email_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-code-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Code Token
         * @description Verify the validity of a signup/login verification token.
         *
         *     Args:
         *         payload (VerifyCodeTokenRequest): JWT token containing the verification code.
         *
         *     Returns:
         *         dict: Response indicating if the token is valid.
         */
        post: operations["verify_code_token_api_v1_auth_verify_code_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Current User
         * @description Retrieve authenticated user profile.
         *
         *     Args:
         *         current_user (User): Authenticated user via dependency.
         *
         *     Returns:
         *         UserBase: Current user information.
         */
        get: operations["read_current_user_api_v1_user_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Images
         * @description Retrieve user's generated images.
         *
         *     Args:
         *         favourites (bool): If True, fetch only favourite images. Defaults to False.
         *         page (int): Page number for pagination. Defaults to 1.
         *         limit (int): Number of images per page. Defaults to 10.
         *         current_user (User): Authenticated user via dependency.
         *         db: Database session.
         */
        get: operations["get_user_images_api_v1_user_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Uploads
         * @description Retrieve URLs of user's uploaded images.
         *
         *     Args:
         *         current_user (User): Authenticated user via dependency.
         *         db: Database session.
         *
         *     Returns:
         *         List[HttpUrl]: List of URLs of uploaded images.
         */
        get: operations["get_user_uploads_api_v1_user_uploads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Credits
         * @description Retrieve user's credits.
         *
         *     Args:
         *         current_user (User): Authenticated user via dependency.
         *
         *     Returns:
         *         int: Number of credits.
         */
        get: operations["get_user_credits_api_v1_user_credits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         *     Args:
         *         file_name (str): Name of the file to upload.
         *         file_type (str): MIME type of the file.
         *         current_user (User): Authenticated user via dependency.
         *
         *     Returns:
         *         ImageUploadResponse: Presigned URL and upload details.
         */
        get: operations["get_presigned_url_api_v1_files_presign_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Image
         * @description Initiate an image generation request.
         *
         *     Args:
         *         data (ImageGenRequest): User input including style ID and input image URL.
         *         background_tasks (BackgroundTasks): FastAPI background task handler.
         *         current_user (User): Authenticated user via dependency.
         *         db: Database session.
         *
         *     Returns:
         *         ImageGenResponse: Contains image_id and confirmation message.
         *
         *     Raises:
         *         NotEnoughCreditsException: If user has not enough credits.
         *         HTTPException: If database record creation fails.
         */
        post: operations["generate_image_api_v1_image_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image/status/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Image Status
         * @description Retrieve image generation status and results.
         *
         *     Args:
         *         image_id (int): ID of the image generation record.
         *         current_user (User): Authenticated user via dependency.
         *         db: Database session.
         *
         *     Returns:
         *         ImageGenStatusResponse: Status and output URL if completed.
         *
         *     Raises:
         *         HTTPException: If image not found or doesn't belong to user.
         */
        get: operations["get_image_status_api_v1_image_status__image_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image/styles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Image Styles
         * @description Retrieve all available hairstyles.
         *
         *     Args:
         *         current_user (User): Authenticated user via dependency.
         *         db: Database session.
         *
         *     Returns:
         *         List[StylesResponse]: List of available styles with metadata.
         */
        get: operations["get_image_styles_api_v1_image_styles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image/like/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Like Image
         * @description Like an image generation record.
         *
         *     Args:
         *         image_id (int): ID of the image generation record.
         *         current_user (User): Authenticated user via dependency.
         *         db: Database session.
         *
         *     Returns:
         *         bool: True if liked successfully, False otherwise.
         *
         *     Raises:
         *         HTTPException: If image not found or doesn't belong to user.
         */
        post: operations["like_image_api_v1_image_like__image_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image/dislike/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dislike Image
         * @description Dislike an image generation record.
         *
         *     Args:
         *         image_id (int): ID of the image generation record.
         *         current_user (User): Authenticated user via dependency.
         *         db: Database session.
         *
         *     Returns:
         *         bool: True if disliked successfully, False otherwise.
         *
         *     Raises:
         *         HTTPException: If image not found or doesn't belong to user.
         */
        post: operations["dislike_image_api_v1_image_dislike__image_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Checkout Session
         * @description Create a checkout session.
         */
        post: operations["create_checkout_session_api_v1_payments_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/transaction/{payment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Transaction By Id
         * @description Get a transaction by id.
         */
        get: operations["get_transaction_by_id_api_v1_payments_transaction__payment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        get: operations["get_transactions_by_user_id_api_v1_payments_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CheckEmailStatusRequest */
        CheckEmailStatusRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** CheckEmailStatusResponse */
        CheckEmailStatusResponse: {
            /** Verified */
            verified: boolean;
        };
        /** CommentResponse */
        CommentResponse: {
            /** Detail */
            detail: string;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageGenRequest */
        ImageGenRequest: {
            /**
             * Image Input Url
             * Format: uri
             */
            image_input_url: string;
            /** Style Id */
            style_id: number;
        };
        /** ImageGenResponse */
        ImageGenResponse: {
            /** Image Id */
            image_id: number;
            /**
             * Message
             * @default Image generation started successfully.
             */
            message: string;
        };
        /** ImageGenStatusResponse */
        ImageGenStatusResponse: {
            /** Id */
            id: number;
            status: components["schemas"]["ImageStatus"];
            /** Description */
            description: string | null;
            /** Output Image Url */
            output_image_url: string | null;
        };
        /**
         * ImageStatus
         * @enum {string}
         */
        ImageStatus: "pending" | "processing" | "completed" | "failed";
        /** ImageUploadResponse */
        ImageUploadResponse: {
            /** File Url */
            file_url: string;
            /** Upload Url */
            upload_url: string;
            /** Key */
            key: string;
            /** Fields */
            fields?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * IntentStatus
         * @enum {string}
         */
        IntentStatus: "succeeded" | "failed" | "cancelled" | "processing" | "requires_customer_action" | "requires_merchant_action" | "requires_payment_method" | "requires_confirmation" | "requires_capture" | "partially_captured" | "partially_captured_and_capturable";
        /** PaymentSessionRequest */
        PaymentSessionRequest: {
            /** Quantity */
            quantity: number;
        };
        /** PaymentSessionResponse */
        PaymentSessionResponse: {
            /** Session Id */
            session_id: string;
            /** Checkout Url */
            checkout_url: string;
        };
        /** RequestLoginTokenRequest */
        RequestLoginTokenRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** RequestLoginTokenResponse */
        RequestLoginTokenResponse: {
            /** Token */
            token: string;
        };
        /** RequestSignupTokenRequest */
        RequestSignupTokenRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** RequestSignupTokenResponse */
        RequestSignupTokenResponse: {
            /** Token */
            token: string;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
            /** Confirm Password */
            confirm_password: string;
        };
        /** SideViewsResponse */
        SideViewsResponse: {
            /**
             * Right View Url
             * Format: uri
             */
            right_view_url: string;
            /**
             * Left View Url
             * Format: uri
             */
            left_view_url: string;
            /**
             * Back View Url
             * Format: uri
             */
            back_view_url: string;
        };
        /** SignupRequest */
        SignupRequest: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Userpic */
            userpic?: string | null;
        };
        /** SignupUserResponse */
        SignupUserResponse: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Verified */
            verified: boolean;
            /** Verify Token */
            verify_token?: string | null;
        };
        /** StylesResponse */
        StylesResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /**
             * Image Url
             * Format: uri
             */
            image_url: string;
        };
        /** TransactionResponse */
        TransactionResponse: {
            /** Id */
            id: number;
            /** Session Id */
            session_id: string;
            /** User Id */
            user_id: number;
            /** Product Id */
            product_id: string;
            /** Amount */
            amount: number;
            status: components["schemas"]["IntentStatus"];
            /** Quantity */
            quantity: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserBase
         * @description Response schema for user's profile.
         */
        UserBase: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Userpic */
            userpic: string | null;
            /** Credits */
            credits: number;
        };
        /**
         * UserImages
         * @description Response schema for user's generated images.
         */
        UserImages: {
            /** Id */
            id: number;
            /** Input Image Url */
            input_image_url: string;
            /** Output Image Url */
            output_image_url: string | null;
            /** Description */
            description: string | null;
            /** Style Name */
            style_name: string;
            side_views: components["schemas"]["SideViewsResponse"] | null;
            status: components["schemas"]["ImageStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Time Taken */
            time_taken: number | null;
        };
        /**
         * UserImagesResponse
         * @description Response schema for user's generated images with model config.
         */
        UserImagesResponse: {
            /** Images */
            images: components["schemas"]["UserImages"][];
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Next Page */
            next_page: number | null;
            /** Total Images */
            total_images: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerifyCodeTokenRequest */
        VerifyCodeTokenRequest: {
            /** Token */
            token: string;
        };
        /** VerifyCodeTokenResponse */
        VerifyCodeTokenResponse: {
            /** Valid */
            valid: boolean;
        };
        /** VerifyLoginRequest */
        VerifyLoginRequest: {
            /** Token */
            token: string;
            /** Code */
            code: string;
        };
        /** VerifyLoginResponse */
        VerifyLoginResponse: {
            /** Verified */
            verified: boolean;
        };
        /** VerifyResetTokenRequest */
        VerifyResetTokenRequest: {
            /** Token */
            token: string;
        };
        /** VerifyResetTokenResponse */
        VerifyResetTokenResponse: {
            /** Valid */
            valid: boolean;
        };
        /** VerifySignupRequest */
        VerifySignupRequest: {
            /** Token */
            token: string;
            /** Code */
            code: string;
        };
        /** VerifySignupResponse */
        VerifySignupResponse: {
            /** Verified */
            verified: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupUserResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    request_signup_token_api_v1_auth_request_signup_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestSignupTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestSignupTokenResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_signup_api_v1_auth_verify_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifySignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifySignupResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    request_login_token_api_v1_auth_request_login_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestLoginTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestLoginTokenResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_login_api_v1_auth_verify_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyLoginResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyLoginResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    google_login_api_v1_auth_google_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    google_auth_api_v1_auth_google_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_reset_token_api_v1_auth_verify_reset_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyResetTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResetTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    check_email_status_api_v1_auth_check_email_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckEmailStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckEmailStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_code_token_api_v1_auth_verify_code_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyCodeTokenResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_current_user_api_v1_user_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_user_images_api_v1_user_images_get: {
        parameters: {
            query?: {
                favourites?: boolean;
                page?: number;
                limit?: number;
                sort_desc?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserImagesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_user_uploads_api_v1_user_uploads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_user_credits_api_v1_user_credits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_presigned_url_api_v1_files_presign_get: {
        parameters: {
            query: {
                file_name: string;
                file_type: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generate_image_api_v1_image_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageGenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageGenResponse"];
                };
            };
            /** @description Not enough credits */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_image_status_api_v1_image_status__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: number;
            };
            cookie?: {
                access_token?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageGenStatusResponse"];
                };
            };
            /** @description Image not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_image_styles_api_v1_image_styles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StylesResponse"][];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    like_image_api_v1_image_like__image_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: number;
            };
            cookie?: {
                access_token?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dislike_image_api_v1_image_dislike__image_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: number;
            };
            cookie?: {
                access_token?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_checkout_session_api_v1_payments_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_transaction_by_id_api_v1_payments_transaction__payment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: string;
            };
            cookie?: {
                access_token?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_transactions_by_user_id_api_v1_payments_transactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
