/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { DeepReadonly, InvalidateQueryFilters, OperationError, OperationInfiniteData, PartialParameters, QueryFiltersByParameters, QueryFiltersByQueryKey, QueryFnOptionsByParameters, QueryFnOptionsByQueryKey, RequestFnResponse, ServiceOperationEnsureInfiniteQueryDataOptions, ServiceOperationEnsureQueryDataOptions, ServiceOperationFetchInfiniteQueryOptions, ServiceOperationFetchQueryOptions, ServiceOperationInfiniteQueryKey, ServiceOperationQueryKey, UseQueryOptionsForUseQueries, UseQueryOptionsForUseSuspenseQuery, WithOptional, QraftServiceOperationsToken } from "@openapi-qraft/tanstack-query-react-types";
import type { CancelOptions, DefinedInitialDataInfiniteOptions, DefinedInitialDataOptions, DefinedUseInfiniteQueryResult, DefinedUseQueryResult, InfiniteQueryPageParamsOptions, InvalidateOptions, NoInfer, QueryState, RefetchOptions, ResetOptions, SetDataOptions, UndefinedInitialDataInfiniteOptions, UndefinedInitialDataOptions, Updater, UseInfiniteQueryResult, UseQueryResult, UseSuspenseInfiniteQueryOptions, UseSuspenseInfiniteQueryResult, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
export interface DefaultService {
    /** @summary Read Root */
    readRootGet: {
        /** @summary Read Root */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: QueryFnOptionsByQueryKey<ReadRootGetSchema, ReadRootGetParameters, TMeta, TSignal> | (QueryFnOptionsByParameters<ReadRootGetParameters, TMeta, TSignal> | void), client?: (schema: ReadRootGetSchema, options: {
            parameters: ReadRootGetParameters;
            signal?: TSignal;
            meta?: TMeta;
        }) => Promise<RequestFnResponse<ReadRootGetData, ReadRootGetError>>): Promise<RequestFnResponse<ReadRootGetData, ReadRootGetError>>;
        /** @summary Read Root */
        getQueryKey(parameters: DeepReadonly<ReadRootGetParameters> | void): ServiceOperationQueryKey<ReadRootGetSchema, ReadRootGetParameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Read Root
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.defaultService.readRootGet.useQuery()
         * ```
         */
        useQuery<TData = ReadRootGetData>(parameters: ServiceOperationQueryKey<ReadRootGetSchema, ReadRootGetParameters> | (DeepReadonly<ReadRootGetParameters> | void), options?: Omit<UndefinedInitialDataOptions<ReadRootGetData, ReadRootGetError, TData, ServiceOperationQueryKey<ReadRootGetSchema, ReadRootGetParameters>>, "queryKey">): UseQueryResult<TData, OperationError<ReadRootGetError>>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Read Root
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.defaultService.readRootGet.useQuery()
         * ```
         */
        useQuery<TData = ReadRootGetData>(parameters: ServiceOperationQueryKey<ReadRootGetSchema, ReadRootGetParameters> | (DeepReadonly<ReadRootGetParameters> | void), options: Omit<DefinedInitialDataOptions<ReadRootGetData, ReadRootGetError, TData, ServiceOperationQueryKey<ReadRootGetSchema, ReadRootGetParameters>>, "queryKey">): DefinedUseQueryResult<TData, OperationError<ReadRootGetError>>;
        /** @summary Read Root */
        getInfiniteQueryKey(parameters: DeepReadonly<ReadRootGetParameters> | void): ServiceOperationInfiniteQueryKey<ReadRootGetSchema, ReadRootGetParameters>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @summary Read Root
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.defaultService.readRootGet.useInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends ReadRootGetParameters, TQueryFnData = ReadRootGetData, TData = OperationInfiniteData<TQueryFnData, ReadRootGetParameters>>(parameters: ServiceOperationInfiniteQueryKey<ReadRootGetSchema, ReadRootGetParameters> | (DeepReadonly<ReadRootGetParameters> | void), options: Omit<UndefinedInitialDataInfiniteOptions<TQueryFnData, ReadRootGetError, TData, ServiceOperationInfiniteQueryKey<ReadRootGetSchema, ReadRootGetParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<TQueryFnData, PartialParameters<DeepReadonly<TPageParam>>>): UseInfiniteQueryResult<TData, OperationError<ReadRootGetError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @summary Read Root
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.defaultService.readRootGet.useInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends ReadRootGetParameters, TQueryFnData = ReadRootGetData, TData = OperationInfiniteData<TQueryFnData, ReadRootGetParameters>>(parameters: ServiceOperationInfiniteQueryKey<ReadRootGetSchema, ReadRootGetParameters> | (DeepReadonly<ReadRootGetParameters> | void), options: Omit<DefinedInitialDataInfiniteOptions<TQueryFnData, ReadRootGetError, TData, ServiceOperationInfiniteQueryKey<ReadRootGetSchema, ReadRootGetParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<ReadRootGetData, PartialParameters<DeepReadonly<TPageParam>>>): DefinedUseInfiniteQueryResult<TData, OperationError<ReadRootGetError>>;
        /**
         * Monitors the number of queries currently fetching, matching the provided filters.
         * Useful for creating loading indicators or performing actions based on active requests.
         *
         * @summary Read Root
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsFetching|`useIsFetching(...)` documentation}
         * @example Checks the total number of queries fetching from the specified service method,
         * both normal and infinite. If no parameters are provided, no filtering is applied.
         * ```ts
         * const readRootGetTotal = qraft.defaultService.readRootGet.useIsFetching()
         * ```
         */
        useIsFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError> | QueryFiltersByQueryKey<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError>): number;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently. This is especially useful for managing complex data dependencies in parallel.
         *
         * @summary Read Root
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQueries|`useQueries(...)` documentation}
         * @example Multiple queries. Returns `data`, `error`, `isSuccess` and other properties.
         * ```ts
         * const readRootGetResults = qraft.defaultService.readRootGet.useQueries({
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * readRootGetResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example Combined results. Only the data will be returned.
         * ```ts
         * const readRootGetCombinedResults = qraft.defaultService.readRootGet.useQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * readRootGetCombinedResults.forEach(data => console.log({ data }));
         * ```
         */
        useQueries<T extends Array<UseQueryOptionsForUseQueries<ReadRootGetSchema, ReadRootGetParameters, ReadRootGetData, ReadRootGetError>>, TCombinedResult = Array<UseQueryResult<ReadRootGetData, ReadRootGetError>>>(options: {
            queries: T;
            combine?: (results: Array<UseQueryResult<ReadRootGetData, ReadRootGetError>>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * Performs asynchronous data fetching with Suspense support.
         * Similar to useQuery but integrates with React Suspense for loading states.
         *
         * @summary Read Root
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQuery|`useSuspenseQuery(...)` documentation}
         * @example Suspense Query without parameters
         * ```ts
         * const data = qraft.defaultService.readRootGet.useSuspenseQuery()
         * ```
         */
        useSuspenseQuery<TData = ReadRootGetData>(parameters: ServiceOperationQueryKey<ReadRootGetSchema, ReadRootGetParameters> | (DeepReadonly<ReadRootGetParameters> | void), options?: Omit<UseSuspenseQueryOptions<ReadRootGetData, ReadRootGetError, TData, ServiceOperationQueryKey<ReadRootGetSchema, ReadRootGetParameters>>, "queryKey">): UseSuspenseQueryResult<TData, OperationError<ReadRootGetError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         * It functions similarly to `useInfiniteQuery`, but with added support for React Suspense.
         *
         * @summary Read Root
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseInfiniteQuery|`useSuspenseInfiniteQuery(...)` documentation}
         *
         * @example Suspense Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.defaultService.readRootGet.useSuspenseInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useSuspenseInfiniteQuery<TPageParam extends ReadRootGetParameters, TData = ReadRootGetData>(parameters: ServiceOperationInfiniteQueryKey<ReadRootGetSchema, ReadRootGetParameters> | (DeepReadonly<ReadRootGetParameters> | void), options: Omit<UseSuspenseInfiniteQueryOptions<ReadRootGetData, ReadRootGetError, OperationInfiniteData<TData, ReadRootGetParameters>, ServiceOperationInfiniteQueryKey<ReadRootGetSchema, ReadRootGetParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<ReadRootGetData, PartialParameters<DeepReadonly<TPageParam>>>): UseSuspenseInfiniteQueryResult<OperationInfiniteData<TData, ReadRootGetParameters>, OperationError<ReadRootGetError>>;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently with Suspense support.
         * Similar to useQueries but integrates with React Suspense for loading states.
         *
         * @summary Read Root
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQueries|`useSuspenseQueries(...)` documentation}
         * @example Basic usage with Suspense
         * ```ts
         * const readRootGetData = qraft.defaultService.readRootGet.useSuspenseQueries({
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * readRootGetResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example With data transformation using combine
         * ```ts
         * const readRootGetCombinedData = qraft.defaultService.readRootGet.useSuspenseQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * readRootGetCombinedData.forEach(data => console.log({ data }));
         * ```
         */
        useSuspenseQueries<T extends Array<UseQueryOptionsForUseSuspenseQuery<ReadRootGetSchema, ReadRootGetParameters, ReadRootGetData, ReadRootGetError>>, TCombinedResult = Array<UseSuspenseQueryResult<ReadRootGetData, ReadRootGetError>>>(options: {
            queries: T;
            combine?: (results: Array<WithOptional<UseSuspenseQueryResult<ReadRootGetData, ReadRootGetError>, "data">>) => TCombinedResult;
        }): TCombinedResult;
        /** @summary Read Root */
        fetchQuery(options: ServiceOperationFetchQueryOptions<ReadRootGetSchema, ReadRootGetData, ReadRootGetParameters, ReadRootGetError> | void): Promise<ReadRootGetData>;
        /** @summary Read Root */
        prefetchQuery(options: ServiceOperationFetchQueryOptions<ReadRootGetSchema, ReadRootGetData, ReadRootGetParameters, ReadRootGetError> | void): Promise<void>;
        /** @summary Read Root */
        ensureQueryData(options: ServiceOperationEnsureQueryDataOptions<ReadRootGetSchema, ReadRootGetData, ReadRootGetParameters, ReadRootGetError> | void): Promise<ReadRootGetData>;
        /** @summary Read Root */
        fetchInfiniteQuery<TPageParam extends ReadRootGetParameters>(options: ServiceOperationFetchInfiniteQueryOptions<ReadRootGetSchema, ReadRootGetData, ReadRootGetParameters, DeepReadonly<TPageParam>, ReadRootGetError> | void): Promise<OperationInfiniteData<ReadRootGetData, ReadRootGetParameters>>;
        /** @summary Read Root */
        prefetchInfiniteQuery<TPageParam extends ReadRootGetParameters>(options: ServiceOperationFetchInfiniteQueryOptions<ReadRootGetSchema, ReadRootGetData, ReadRootGetParameters, DeepReadonly<TPageParam>, ReadRootGetError> | void): Promise<void>;
        /** @summary Read Root */
        ensureInfiniteQueryData<TPageParam extends ReadRootGetParameters>(options: ServiceOperationEnsureInfiniteQueryDataOptions<ReadRootGetSchema, ReadRootGetData, ReadRootGetParameters, DeepReadonly<TPageParam>, ReadRootGetError> | void): Promise<OperationInfiniteData<ReadRootGetData, ReadRootGetParameters>>;
        /** @summary Read Root */
        getQueryData(parameters: ServiceOperationQueryKey<ReadRootGetSchema, ReadRootGetParameters> | (DeepReadonly<ReadRootGetParameters> | void)): ReadRootGetData | undefined;
        /** @summary Read Root */
        getInfiniteQueryData(parameters: ServiceOperationInfiniteQueryKey<ReadRootGetSchema, ReadRootGetParameters> | (DeepReadonly<ReadRootGetParameters> | void)): OperationInfiniteData<ReadRootGetData, ReadRootGetParameters> | undefined;
        /** @summary Read Root */
        getQueriesData<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError> | QueryFiltersByQueryKey<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError>): TInfinite extends true ? Array<[
            queryKey: ServiceOperationInfiniteQueryKey<ReadRootGetSchema, ReadRootGetParameters>,
            data: NoInfer<OperationInfiniteData<ReadRootGetData, ReadRootGetParameters>> | undefined
        ]> : Array<[
            queryKey: ServiceOperationQueryKey<ReadRootGetSchema, ReadRootGetParameters>,
            data: ReadRootGetData | undefined
        ]>;
        /** @summary Read Root */
        getQueryState(parameters: ServiceOperationQueryKey<ReadRootGetSchema, ReadRootGetParameters> | (DeepReadonly<ReadRootGetParameters> | void)): QueryState<ReadRootGetData, ReadRootGetError> | undefined;
        /** @summary Read Root */
        getInfiniteQueryState(parameters: DeepReadonly<ReadRootGetParameters> | ServiceOperationInfiniteQueryKey<ReadRootGetSchema, ReadRootGetParameters> | void): QueryState<OperationInfiniteData<ReadRootGetData, ReadRootGetParameters>, ReadRootGetError> | undefined;
        /** @summary Read Root */
        setQueryData(parameters: (DeepReadonly<ReadRootGetParameters> | undefined) | ServiceOperationQueryKey<ReadRootGetSchema, ReadRootGetParameters>, updater: Updater<NoInfer<ReadRootGetData> | undefined, NoInfer<DeepReadonly<ReadRootGetData>> | undefined>, options?: SetDataOptions): ReadRootGetData | undefined;
        /** @summary Read Root */
        setInfiniteQueryData(parameters: (DeepReadonly<ReadRootGetParameters> | undefined) | ServiceOperationInfiniteQueryKey<ReadRootGetSchema, ReadRootGetParameters>, updater: Updater<NoInfer<OperationInfiniteData<ReadRootGetData, ReadRootGetParameters>> | undefined, NoInfer<DeepReadonly<OperationInfiniteData<ReadRootGetData, ReadRootGetParameters>>> | undefined>, options?: SetDataOptions): OperationInfiniteData<ReadRootGetData, ReadRootGetParameters> | undefined;
        /** @summary Read Root */
        setQueriesData<TInfinite extends boolean = false>(filters: QueryFiltersByParameters<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError> | QueryFiltersByQueryKey<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError>, updater: Updater<NoInfer<ReadRootGetData> | undefined, NoInfer<ReadRootGetData> | undefined>, options?: SetDataOptions): Array<ReadRootGetData | undefined>;
        /** @summary Read Root */
        invalidateQueries<TInfinite extends boolean = false>(filters?: InvalidateQueryFilters<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError>, options?: InvalidateOptions): Promise<void>;
        /** @summary Read Root */
        refetchQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError> | QueryFiltersByQueryKey<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError>, options?: RefetchOptions): Promise<void>;
        /** @summary Read Root */
        cancelQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError> | QueryFiltersByQueryKey<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError>, options?: CancelOptions): Promise<void>;
        /** @summary Read Root */
        removeQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError> | QueryFiltersByQueryKey<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError>): void;
        /** @summary Read Root */
        resetQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError> | QueryFiltersByQueryKey<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError>, options?: ResetOptions): Promise<void>;
        /** @summary Read Root */
        isFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError> | QueryFiltersByQueryKey<ReadRootGetSchema, ReadRootGetData, TInfinite, ReadRootGetParameters, ReadRootGetError>): number;
        schema: ReadRootGetSchema;
        types: {
            parameters: ReadRootGetParameters;
            data: ReadRootGetData;
            error: ReadRootGetError;
        };
    };
}
/** @summary Read Root */
export const readRootGet = {
    schema: {
        method: "get",
        url: "/"
    }
} as {
    schema: ReadRootGetSchema;
    [QraftServiceOperationsToken]: DefaultService["readRootGet"];
};
export const defaultService = {
    readRootGet
} as const;
type ReadRootGetSchema = {
    method: "get";
    url: "/";
};
type ReadRootGetParameters = undefined;
type ReadRootGetData = paths["/"]["get"]["responses"]["200"]["content"]["text/html"];
type ReadRootGetError = unknown;
