/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { DeepReadonly, InvalidateQueryFilters, OperationError, OperationInfiniteData, PartialParameters, QueryFiltersByParameters, QueryFiltersByQueryKey, QueryFnOptionsByParameters, QueryFnOptionsByQueryKey, RequestFnResponse, ServiceOperationEnsureInfiniteQueryDataOptions, ServiceOperationEnsureQueryDataOptions, ServiceOperationFetchInfiniteQueryOptions, ServiceOperationFetchQueryOptions, ServiceOperationInfiniteQueryKey, ServiceOperationQueryKey, UseQueryOptionsForUseQueries, UseQueryOptionsForUseSuspenseQuery, WithOptional, QraftServiceOperationsToken } from "@openapi-qraft/tanstack-query-react-types";
import type { CancelOptions, DefinedInitialDataInfiniteOptions, DefinedInitialDataOptions, DefinedUseInfiniteQueryResult, DefinedUseQueryResult, InfiniteQueryPageParamsOptions, InvalidateOptions, NoInfer, QueryState, RefetchOptions, ResetOptions, SetDataOptions, UndefinedInitialDataInfiniteOptions, UndefinedInitialDataOptions, Updater, UseInfiniteQueryResult, UseQueryResult, UseSuspenseInfiniteQueryOptions, UseSuspenseInfiniteQueryResult, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
export interface FilesService {
    /**
     * @summary Get Presigned Url
     * @description Generate presigned URL for direct S3 upload.
     *
     * Args:
     *     file_name (str): Name of the file to upload.
     *     file_type (str): MIME type of the file.
     *     current_user (User): Authenticated user via dependency.
     *
     * Returns:
     *     ImageUploadResponse: Presigned URL and upload details.
     */
    getPresignedUrlApiV1FilesPresignGet: {
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: QueryFnOptionsByQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters, TMeta, TSignal> | (QueryFnOptionsByParameters<GetPresignedUrlApiV1FilesPresignGetParameters, TMeta, TSignal>), client?: (schema: GetPresignedUrlApiV1FilesPresignGetSchema, options: {
            parameters: GetPresignedUrlApiV1FilesPresignGetParameters;
            signal?: TSignal;
            meta?: TMeta;
        }) => Promise<RequestFnResponse<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetError>>): Promise<RequestFnResponse<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetError>>;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        getQueryKey(parameters: DeepReadonly<GetPresignedUrlApiV1FilesPresignGetParameters>): ServiceOperationQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.filesService.getPresignedUrlApiV1FilesPresignGet.useQuery({
         *     query: {
         *         file_name: fileName,
         *         file_type: fileType
         *     },
         *     cookie: {
         *         access_token: accessToken
         *     }
         * })
         * ```
         */
        useQuery<TData = GetPresignedUrlApiV1FilesPresignGetData>(parameters: ServiceOperationQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters> | (DeepReadonly<GetPresignedUrlApiV1FilesPresignGetParameters>), options?: Omit<UndefinedInitialDataOptions<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetError, TData, ServiceOperationQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters>>, "queryKey">): UseQueryResult<TData, OperationError<GetPresignedUrlApiV1FilesPresignGetError>>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.filesService.getPresignedUrlApiV1FilesPresignGet.useQuery({
         *     query: {
         *         file_name: fileName,
         *         file_type: fileType
         *     },
         *     cookie: {
         *         access_token: accessToken
         *     }
         * })
         * ```
         */
        useQuery<TData = GetPresignedUrlApiV1FilesPresignGetData>(parameters: ServiceOperationQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters> | (DeepReadonly<GetPresignedUrlApiV1FilesPresignGetParameters>), options: Omit<DefinedInitialDataOptions<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetError, TData, ServiceOperationQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters>>, "queryKey">): DefinedUseQueryResult<TData, OperationError<GetPresignedUrlApiV1FilesPresignGetError>>;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        getInfiniteQueryKey(parameters: DeepReadonly<GetPresignedUrlApiV1FilesPresignGetParameters>): ServiceOperationInfiniteQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.filesService.getPresignedUrlApiV1FilesPresignGet.useInfiniteQuery({
         *     query: {
         *         file_name: fileName,
         *         file_type: fileType
         *     },
         *     cookie: {
         *         access_token: accessToken
         *     }
         * }, {
         *     initialPageParam: {
         *         query: {
         *             file_name: initialFileName,
         *             file_type: initialFileType
         *         }
         *     },
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends GetPresignedUrlApiV1FilesPresignGetParameters, TQueryFnData = GetPresignedUrlApiV1FilesPresignGetData, TData = OperationInfiniteData<TQueryFnData, GetPresignedUrlApiV1FilesPresignGetParameters>>(parameters: ServiceOperationInfiniteQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters> | (DeepReadonly<GetPresignedUrlApiV1FilesPresignGetParameters>), options: Omit<UndefinedInitialDataInfiniteOptions<TQueryFnData, GetPresignedUrlApiV1FilesPresignGetError, TData, ServiceOperationInfiniteQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<TQueryFnData, PartialParameters<DeepReadonly<TPageParam>>>): UseInfiniteQueryResult<TData, OperationError<GetPresignedUrlApiV1FilesPresignGetError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.filesService.getPresignedUrlApiV1FilesPresignGet.useInfiniteQuery({
         *     query: {
         *         file_name: fileName,
         *         file_type: fileType
         *     },
         *     cookie: {
         *         access_token: accessToken
         *     }
         * }, {
         *     initialPageParam: {
         *         query: {
         *             file_name: initialFileName,
         *             file_type: initialFileType
         *         }
         *     },
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends GetPresignedUrlApiV1FilesPresignGetParameters, TQueryFnData = GetPresignedUrlApiV1FilesPresignGetData, TData = OperationInfiniteData<TQueryFnData, GetPresignedUrlApiV1FilesPresignGetParameters>>(parameters: ServiceOperationInfiniteQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters> | (DeepReadonly<GetPresignedUrlApiV1FilesPresignGetParameters>), options: Omit<DefinedInitialDataInfiniteOptions<TQueryFnData, GetPresignedUrlApiV1FilesPresignGetError, TData, ServiceOperationInfiniteQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<GetPresignedUrlApiV1FilesPresignGetData, PartialParameters<DeepReadonly<TPageParam>>>): DefinedUseInfiniteQueryResult<TData, OperationError<GetPresignedUrlApiV1FilesPresignGetError>>;
        /**
         * Monitors the number of queries currently fetching, matching the provided filters.
         * Useful for creating loading indicators or performing actions based on active requests.
         *
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsFetching|`useIsFetching(...)` documentation}
         * @example Checks the total number of queries fetching from the specified service method,
         * both normal and infinite. If no parameters are provided, no filtering is applied.
         * ```ts
         * const getPresignedUrlApiV1FilesPresignGetTotal = qraft.filesService.getPresignedUrlApiV1FilesPresignGet.useIsFetching()
         * ```
         * @example Checks the number of normal queries fetching with the specified parameters.
         * ```ts
         * const getPresignedUrlApiV1FilesPresignGetByParametersTotal = qraft.filesService.getPresignedUrlApiV1FilesPresignGet.useIsFetching({
         *     infinite: false,
         *     parameters: {
         *         query: {
         *             file_name: fileName,
         *             file_type: fileType
         *         },
         *         cookie: {
         *             access_token: accessToken
         *         }
         *     }
         * })
         * ```
         */
        useIsFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError> | QueryFiltersByQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError>): number;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently. This is especially useful for managing complex data dependencies in parallel.
         *
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQueries|`useQueries(...)` documentation}
         * @example Multiple queries. Returns `data`, `error`, `isSuccess` and other properties.
         * ```ts
         * const getPresignedUrlApiV1FilesPresignGetResults = qraft.filesService.getPresignedUrlApiV1FilesPresignGet.useQueries({
         *     queries: [
         *         {
         *             query: {
         *                 file_name: fileName1,
         *                 file_type: fileType1
         *             },
         *             cookie: {
         *                 access_token: accessToken1
         *             }
         *         },
         *         {
         *             query: {
         *                 file_name: fileName2,
         *                 file_type: fileType2
         *             },
         *             cookie: {
         *                 access_token: accessToken2
         *             }
         *         }
         *     ]
         * });
         * getPresignedUrlApiV1FilesPresignGetResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example Combined results. Only the data will be returned.
         * ```ts
         * const getPresignedUrlApiV1FilesPresignGetCombinedResults = qraft.filesService.getPresignedUrlApiV1FilesPresignGet.useQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {
         *             query: {
         *                 file_name: fileName1,
         *                 file_type: fileType1
         *             },
         *             cookie: {
         *                 access_token: accessToken1
         *             }
         *         },
         *         {
         *             query: {
         *                 file_name: fileName2,
         *                 file_type: fileType2
         *             },
         *             cookie: {
         *                 access_token: accessToken2
         *             }
         *         }
         *     ]
         * });
         * getPresignedUrlApiV1FilesPresignGetCombinedResults.forEach(data => console.log({ data }));
         * ```
         */
        useQueries<T extends Array<UseQueryOptionsForUseQueries<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetError>>, TCombinedResult = Array<UseQueryResult<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetError>>>(options: {
            queries: T;
            combine?: (results: Array<UseQueryResult<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetError>>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * Performs asynchronous data fetching with Suspense support.
         * Similar to useQuery but integrates with React Suspense for loading states.
         *
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQuery|`useSuspenseQuery(...)` documentation}
         * @example Suspense Query with parameters
         * ```ts
         * const data = qraft.filesService.getPresignedUrlApiV1FilesPresignGet.useSuspenseQuery({
         *     query: {
         *         file_name: fileName,
         *         file_type: fileType
         *     },
         *     cookie: {
         *         access_token: accessToken
         *     }
         * })
         * ```
         */
        useSuspenseQuery<TData = GetPresignedUrlApiV1FilesPresignGetData>(parameters: ServiceOperationQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters> | (DeepReadonly<GetPresignedUrlApiV1FilesPresignGetParameters>), options?: Omit<UseSuspenseQueryOptions<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetError, TData, ServiceOperationQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters>>, "queryKey">): UseSuspenseQueryResult<TData, OperationError<GetPresignedUrlApiV1FilesPresignGetError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         * It functions similarly to `useInfiniteQuery`, but with added support for React Suspense.
         *
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseInfiniteQuery|`useSuspenseInfiniteQuery(...)` documentation}
         *
         * @example Suspense Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.filesService.getPresignedUrlApiV1FilesPresignGet.useSuspenseInfiniteQuery({
         *     query: {
         *         file_name: fileName,
         *         file_type: fileType
         *     },
         *     cookie: {
         *         access_token: accessToken
         *     }
         * }, {
         *     initialPageParam: {
         *         query: {
         *             file_name: initialFileName,
         *             file_type: initialFileType
         *         }
         *     },
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useSuspenseInfiniteQuery<TPageParam extends GetPresignedUrlApiV1FilesPresignGetParameters, TData = GetPresignedUrlApiV1FilesPresignGetData>(parameters: ServiceOperationInfiniteQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters> | (DeepReadonly<GetPresignedUrlApiV1FilesPresignGetParameters>), options: Omit<UseSuspenseInfiniteQueryOptions<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetError, OperationInfiniteData<TData, GetPresignedUrlApiV1FilesPresignGetParameters>, ServiceOperationInfiniteQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<GetPresignedUrlApiV1FilesPresignGetData, PartialParameters<DeepReadonly<TPageParam>>>): UseSuspenseInfiniteQueryResult<OperationInfiniteData<TData, GetPresignedUrlApiV1FilesPresignGetParameters>, OperationError<GetPresignedUrlApiV1FilesPresignGetError>>;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently with Suspense support.
         * Similar to useQueries but integrates with React Suspense for loading states.
         *
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQueries|`useSuspenseQueries(...)` documentation}
         * @example Basic usage with Suspense
         * ```ts
         * const getPresignedUrlApiV1FilesPresignGetData = qraft.filesService.getPresignedUrlApiV1FilesPresignGet.useSuspenseQueries({
         *     queries: [
         *         {
         *             query: {
         *                 file_name: fileName1,
         *                 file_type: fileType1
         *             },
         *             cookie: {
         *                 access_token: accessToken1
         *             }
         *         },
         *         {
         *             query: {
         *                 file_name: fileName2,
         *                 file_type: fileType2
         *             },
         *             cookie: {
         *                 access_token: accessToken2
         *             }
         *         }
         *     ]
         * });
         * getPresignedUrlApiV1FilesPresignGetResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example With data transformation using combine
         * ```ts
         * const getPresignedUrlApiV1FilesPresignGetCombinedData = qraft.filesService.getPresignedUrlApiV1FilesPresignGet.useSuspenseQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {
         *             query: {
         *                 file_name: fileName1,
         *                 file_type: fileType1
         *             },
         *             cookie: {
         *                 access_token: accessToken1
         *             }
         *         },
         *         {
         *             query: {
         *                 file_name: fileName2,
         *                 file_type: fileType2
         *             },
         *             cookie: {
         *                 access_token: accessToken2
         *             }
         *         }
         *     ]
         * });
         * getPresignedUrlApiV1FilesPresignGetCombinedData.forEach(data => console.log({ data }));
         * ```
         */
        useSuspenseQueries<T extends Array<UseQueryOptionsForUseSuspenseQuery<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetError>>, TCombinedResult = Array<UseSuspenseQueryResult<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetError>>>(options: {
            queries: T;
            combine?: (results: Array<WithOptional<UseSuspenseQueryResult<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetError>, "data">>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        fetchQuery(options: ServiceOperationFetchQueryOptions<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError>): Promise<GetPresignedUrlApiV1FilesPresignGetData>;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        prefetchQuery(options: ServiceOperationFetchQueryOptions<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError>): Promise<void>;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        ensureQueryData(options: ServiceOperationEnsureQueryDataOptions<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError>): Promise<GetPresignedUrlApiV1FilesPresignGetData>;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        fetchInfiniteQuery<TPageParam extends GetPresignedUrlApiV1FilesPresignGetParameters>(options: ServiceOperationFetchInfiniteQueryOptions<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetParameters, DeepReadonly<TPageParam>, GetPresignedUrlApiV1FilesPresignGetError>): Promise<OperationInfiniteData<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetParameters>>;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        prefetchInfiniteQuery<TPageParam extends GetPresignedUrlApiV1FilesPresignGetParameters>(options: ServiceOperationFetchInfiniteQueryOptions<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetParameters, DeepReadonly<TPageParam>, GetPresignedUrlApiV1FilesPresignGetError>): Promise<void>;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        ensureInfiniteQueryData<TPageParam extends GetPresignedUrlApiV1FilesPresignGetParameters>(options: ServiceOperationEnsureInfiniteQueryDataOptions<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetParameters, DeepReadonly<TPageParam>, GetPresignedUrlApiV1FilesPresignGetError>): Promise<OperationInfiniteData<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetParameters>>;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        getQueryData(parameters: ServiceOperationQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters> | (DeepReadonly<GetPresignedUrlApiV1FilesPresignGetParameters>)): GetPresignedUrlApiV1FilesPresignGetData | undefined;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        getInfiniteQueryData(parameters: ServiceOperationInfiniteQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters> | (DeepReadonly<GetPresignedUrlApiV1FilesPresignGetParameters>)): OperationInfiniteData<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetParameters> | undefined;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        getQueriesData<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError> | QueryFiltersByQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError>): TInfinite extends true ? Array<[
            queryKey: ServiceOperationInfiniteQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters>,
            data: NoInfer<OperationInfiniteData<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetParameters>> | undefined
        ]> : Array<[
            queryKey: ServiceOperationQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters>,
            data: GetPresignedUrlApiV1FilesPresignGetData | undefined
        ]>;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        getQueryState(parameters: ServiceOperationQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters> | (DeepReadonly<GetPresignedUrlApiV1FilesPresignGetParameters>)): QueryState<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetError> | undefined;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        getInfiniteQueryState(parameters: DeepReadonly<GetPresignedUrlApiV1FilesPresignGetParameters> | ServiceOperationInfiniteQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters>): QueryState<OperationInfiniteData<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetParameters>, GetPresignedUrlApiV1FilesPresignGetError> | undefined;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        setQueryData(parameters: (DeepReadonly<GetPresignedUrlApiV1FilesPresignGetParameters>) | ServiceOperationQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters>, updater: Updater<NoInfer<GetPresignedUrlApiV1FilesPresignGetData> | undefined, NoInfer<DeepReadonly<GetPresignedUrlApiV1FilesPresignGetData>> | undefined>, options?: SetDataOptions): GetPresignedUrlApiV1FilesPresignGetData | undefined;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        setInfiniteQueryData(parameters: (DeepReadonly<GetPresignedUrlApiV1FilesPresignGetParameters>) | ServiceOperationInfiniteQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetParameters>, updater: Updater<NoInfer<OperationInfiniteData<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetParameters>> | undefined, NoInfer<DeepReadonly<OperationInfiniteData<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetParameters>>> | undefined>, options?: SetDataOptions): OperationInfiniteData<GetPresignedUrlApiV1FilesPresignGetData, GetPresignedUrlApiV1FilesPresignGetParameters> | undefined;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        setQueriesData<TInfinite extends boolean = false>(filters: QueryFiltersByParameters<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError> | QueryFiltersByQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError>, updater: Updater<NoInfer<GetPresignedUrlApiV1FilesPresignGetData> | undefined, NoInfer<GetPresignedUrlApiV1FilesPresignGetData> | undefined>, options?: SetDataOptions): Array<GetPresignedUrlApiV1FilesPresignGetData | undefined>;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        invalidateQueries<TInfinite extends boolean = false>(filters?: InvalidateQueryFilters<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError>, options?: InvalidateOptions): Promise<void>;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        refetchQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError> | QueryFiltersByQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError>, options?: RefetchOptions): Promise<void>;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        cancelQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError> | QueryFiltersByQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError>, options?: CancelOptions): Promise<void>;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        removeQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError> | QueryFiltersByQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError>): void;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        resetQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError> | QueryFiltersByQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError>, options?: ResetOptions): Promise<void>;
        /**
         * @summary Get Presigned Url
         * @description Generate presigned URL for direct S3 upload.
         *
         * Args:
         *     file_name (str): Name of the file to upload.
         *     file_type (str): MIME type of the file.
         *     current_user (User): Authenticated user via dependency.
         *
         * Returns:
         *     ImageUploadResponse: Presigned URL and upload details.
         */
        isFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError> | QueryFiltersByQueryKey<GetPresignedUrlApiV1FilesPresignGetSchema, GetPresignedUrlApiV1FilesPresignGetData, TInfinite, GetPresignedUrlApiV1FilesPresignGetParameters, GetPresignedUrlApiV1FilesPresignGetError>): number;
        schema: GetPresignedUrlApiV1FilesPresignGetSchema;
        types: {
            parameters: GetPresignedUrlApiV1FilesPresignGetParameters;
            data: GetPresignedUrlApiV1FilesPresignGetData;
            error: GetPresignedUrlApiV1FilesPresignGetError;
        };
    };
}
/**
 * @summary Get Presigned Url
 * @description Generate presigned URL for direct S3 upload.
 *
 * Args:
 *     file_name (str): Name of the file to upload.
 *     file_type (str): MIME type of the file.
 *     current_user (User): Authenticated user via dependency.
 *
 * Returns:
 *     ImageUploadResponse: Presigned URL and upload details.
 */
export const getPresignedUrlApiV1FilesPresignGet = {
    schema: {
        method: "get",
        url: "/api/v1/files/presign"
    }
} as {
    schema: GetPresignedUrlApiV1FilesPresignGetSchema;
    [QraftServiceOperationsToken]: FilesService["getPresignedUrlApiV1FilesPresignGet"];
};
export const filesService = {
    getPresignedUrlApiV1FilesPresignGet
} as const;
type GetPresignedUrlApiV1FilesPresignGetSchema = {
    method: "get";
    url: "/api/v1/files/presign";
};
type GetPresignedUrlApiV1FilesPresignGetParameters = paths["/api/v1/files/presign"]["get"]["parameters"];
type GetPresignedUrlApiV1FilesPresignGetData = paths["/api/v1/files/presign"]["get"]["responses"]["200"]["content"]["application/json"];
type GetPresignedUrlApiV1FilesPresignGetError = paths["/api/v1/files/presign"]["get"]["responses"]["422"]["content"]["application/json"] | null;
