/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { AuthService } from "./AuthService";
import { authService } from "./AuthService";
import type { UserService } from "./UserService";
import { userService } from "./UserService";
import type { FilesService } from "./FilesService";
import { filesService } from "./FilesService";
import type { ImageService } from "./ImageService";
import { imageService } from "./ImageService";
import type { DefaultService } from "./DefaultService";
import { defaultService } from "./DefaultService";
export type Services = {
    auth: AuthService;
    user: UserService;
    files: FilesService;
    image: ImageService;
    default: DefaultService;
};
export const services = {
    auth: authService,
    user: userService,
    files: filesService,
    image: imageService,
    default: defaultService
} as const;
