/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { DeepReadonly, InvalidateQueryFilters, MutationFiltersByMutationKey, MutationFiltersByParameters, MutationVariables, OperationError, OperationInfiniteData, PartialParameters, QueryFiltersByParameters, QueryFiltersByQueryKey, QueryFnOptionsByParameters, QueryFnOptionsByQueryKey, RequestFnResponse, ServiceOperationEnsureInfiniteQueryDataOptions, ServiceOperationEnsureQueryDataOptions, ServiceOperationFetchInfiniteQueryOptions, ServiceOperationFetchQueryOptions, ServiceOperationInfiniteQueryKey, ServiceOperationMutationFnOptions, ServiceOperationMutationKey, ServiceOperationQueryKey, ServiceOperationUseMutationOptions, UseQueryOptionsForUseQueries, UseQueryOptionsForUseSuspenseQuery, WithOptional, QraftServiceOperationsToken } from "@openapi-qraft/tanstack-query-react-types";
import type { CancelOptions, DefinedInitialDataInfiniteOptions, DefinedInitialDataOptions, DefinedUseInfiniteQueryResult, DefinedUseQueryResult, InfiniteQueryPageParamsOptions, InvalidateOptions, Mutation, MutationCache, MutationState, NoInfer, QueryState, RefetchOptions, ResetOptions, SetDataOptions, UndefinedInitialDataInfiniteOptions, UndefinedInitialDataOptions, Updater, UseInfiniteQueryResult, UseMutationResult, UseQueryResult, UseSuspenseInfiniteQueryOptions, UseSuspenseInfiniteQueryResult, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
export interface PaymentsService {
    /**
     * @summary Create Checkout Session
     * @description Create a checkout session.
     */
    createCheckoutSessionApiV1PaymentsCheckoutPost: {
        /**
         * @summary Create Checkout Session
         * @description Create a checkout session.
         */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: ServiceOperationMutationFnOptions<CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters, TMeta, TSignal>, client?: (schema: CreateCheckoutSessionApiV1PaymentsCheckoutPostSchema, options: ServiceOperationMutationFnOptions<CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters, TMeta, TSignal>) => Promise<RequestFnResponse<CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostError>>): Promise<RequestFnResponse<CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostError>>;
        /**
         * @summary Create Checkout Session
         * @description Create a checkout session.
         */
        getMutationKey(parameters: DeepReadonly<CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters> | void): ServiceOperationMutationKey<CreateCheckoutSessionApiV1PaymentsCheckoutPostSchema, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @summary Create Checkout Session
         * @description Create a checkout session.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.paymentsService.createCheckoutSessionApiV1PaymentsCheckoutPost.useMutation({
         *     cookie: {
         *         access_token: accessToken
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.paymentsService.createCheckoutSessionApiV1PaymentsCheckoutPost.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     cookie: {
         *         access_token: accessToken
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, TContext = unknown>(parameters: DeepReadonly<CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters>, options?: ServiceOperationUseMutationOptions<CreateCheckoutSessionApiV1PaymentsCheckoutPostSchema, CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters, TVariables, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, TContext>): UseMutationResult<CreateCheckoutSessionApiV1PaymentsCheckoutPostData, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, TVariables, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @summary Create Checkout Session
         * @description Create a checkout session.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.paymentsService.createCheckoutSessionApiV1PaymentsCheckoutPost.useMutation({
         *     cookie: {
         *         access_token: accessToken
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.paymentsService.createCheckoutSessionApiV1PaymentsCheckoutPost.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     cookie: {
         *         access_token: accessToken
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<CreateCheckoutSessionApiV1PaymentsCheckoutPostSchema, CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters, TVariables, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, TContext>): UseMutationResult<CreateCheckoutSessionApiV1PaymentsCheckoutPostData, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @summary Create Checkout Session
         * @description Create a checkout session.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const createCheckoutSessionApiV1PaymentsCheckoutPostTotal = qraft.paymentsService.createCheckoutSessionApiV1PaymentsCheckoutPost.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const createCheckoutSessionApiV1PaymentsCheckoutPostTotal = qraft.paymentsService.createCheckoutSessionApiV1PaymentsCheckoutPost.useIsMutating({
         *     parameters: {
         *         cookie: {
         *             access_token: accessToken
         *         }
         *     }
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, TContext> | MutationFiltersByMutationKey<CreateCheckoutSessionApiV1PaymentsCheckoutPostSchema, CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, TContext>): number;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @summary Create Checkout Session
         * @description Create a checkout session.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const createCheckoutSessionApiV1PaymentsCheckoutPostPendingMutationVariables = qraft.paymentsService.createCheckoutSessionApiV1PaymentsCheckoutPost.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const createCheckoutSessionApiV1PaymentsCheckoutPostMutationData = qraft.paymentsService.createCheckoutSessionApiV1PaymentsCheckoutPost.useMutationState({
         *     filters: {
         *         parameters: {
         *             cookie: {
         *                 access_token: accessToken
         *             }
         *         }
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<CreateCheckoutSessionApiV1PaymentsCheckoutPostData, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, MutationVariables<CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, TContext> | MutationFiltersByMutationKey<CreateCheckoutSessionApiV1PaymentsCheckoutPostSchema, CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, TContext>;
            select?: (mutation: Mutation<CreateCheckoutSessionApiV1PaymentsCheckoutPostData, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, MutationVariables<CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters>, TContext>) => TResult;
        }): Array<TResult>;
        /**
         * @summary Create Checkout Session
         * @description Create a checkout session.
         */
        isMutating<TContext>(filters?: MutationFiltersByParameters<CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, TContext> | MutationFiltersByMutationKey<CreateCheckoutSessionApiV1PaymentsCheckoutPostSchema, CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, TContext>): number;
        /**
         * Returns a `MutationCache` object that provides access to mutation cache operations
         * for the specific endpoint.
         *
         * @summary Create Checkout Session
         * @description Create a checkout session.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/query-client/getMutationCache|`getMutationCache(...)` documentation}
         *
         * @example Find a mutation with specific parameters
         * ```ts
         * const mutationCache = qraft.paymentsService.createCheckoutSessionApiV1PaymentsCheckoutPost.getMutationCache();
         * const mutation = mutationCache.find({
         *     parameters: {
         *         cookie: {
         *             access_token: accessToken
         *         }
         *     }
         * });
         * ```
         *
         * @example Find all mutations for the endpoint
         * ```ts
         * const mutationCache = qraft.paymentsService.createCheckoutSessionApiV1PaymentsCheckoutPost.getMutationCache();
         * const mutations = mutationCache.findAll();
         * ```
         */
        getMutationCache(): Omit<MutationCache, "find" | "findAll"> & {
            find<TContext = unknown>(filters: MutationFiltersByParameters<CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, TContext> | MutationFiltersByMutationKey<CreateCheckoutSessionApiV1PaymentsCheckoutPostSchema, CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, TContext>): Mutation<CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostError, MutationVariables<CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters>, TContext> | undefined;
            findAll<TContext = unknown>(filters?: MutationFiltersByParameters<CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, TContext> | MutationFiltersByMutationKey<CreateCheckoutSessionApiV1PaymentsCheckoutPostSchema, CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters, OperationError<CreateCheckoutSessionApiV1PaymentsCheckoutPostError>, TContext>): Array<Mutation<CreateCheckoutSessionApiV1PaymentsCheckoutPostData, CreateCheckoutSessionApiV1PaymentsCheckoutPostError, MutationVariables<CreateCheckoutSessionApiV1PaymentsCheckoutPostBody, CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters>, TContext>>;
        };
        schema: CreateCheckoutSessionApiV1PaymentsCheckoutPostSchema;
        types: {
            parameters: CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters;
            data: CreateCheckoutSessionApiV1PaymentsCheckoutPostData;
            error: CreateCheckoutSessionApiV1PaymentsCheckoutPostError;
            body: CreateCheckoutSessionApiV1PaymentsCheckoutPostBody;
        };
    };
    /**
     * @summary Get Transaction By Id
     * @description Get a transaction by id.
     */
    getTransactionByIdApiV1PaymentsTransactionPaymentIdGet: {
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: QueryFnOptionsByQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, TMeta, TSignal> | (QueryFnOptionsByParameters<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, TMeta, TSignal>), client?: (schema: GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, options: {
            parameters: GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters;
            signal?: TSignal;
            meta?: TMeta;
        }) => Promise<RequestFnResponse<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>>): Promise<RequestFnResponse<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>>;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        getQueryKey(parameters: DeepReadonly<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>): ServiceOperationQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.paymentsService.getTransactionByIdApiV1PaymentsTransactionPaymentIdGet.useQuery({
         *     path: {
         *         payment_id: paymentId
         *     },
         *     cookie: {
         *         access_token: accessToken
         *     }
         * })
         * ```
         */
        useQuery<TData = GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData>(parameters: ServiceOperationQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters> | (DeepReadonly<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>), options?: Omit<UndefinedInitialDataOptions<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError, TData, ServiceOperationQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>>, "queryKey">): UseQueryResult<TData, OperationError<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.paymentsService.getTransactionByIdApiV1PaymentsTransactionPaymentIdGet.useQuery({
         *     path: {
         *         payment_id: paymentId
         *     },
         *     cookie: {
         *         access_token: accessToken
         *     }
         * })
         * ```
         */
        useQuery<TData = GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData>(parameters: ServiceOperationQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters> | (DeepReadonly<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>), options: Omit<DefinedInitialDataOptions<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError, TData, ServiceOperationQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>>, "queryKey">): DefinedUseQueryResult<TData, OperationError<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>>;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        getInfiniteQueryKey(parameters: DeepReadonly<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>): ServiceOperationInfiniteQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.paymentsService.getTransactionByIdApiV1PaymentsTransactionPaymentIdGet.useInfiniteQuery({
         *     path: {
         *         payment_id: paymentId
         *     },
         *     cookie: {
         *         access_token: accessToken
         *     }
         * }, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, TQueryFnData = GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TData = OperationInfiniteData<TQueryFnData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>>(parameters: ServiceOperationInfiniteQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters> | (DeepReadonly<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>), options: Omit<UndefinedInitialDataInfiniteOptions<TQueryFnData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError, TData, ServiceOperationInfiniteQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<TQueryFnData, PartialParameters<DeepReadonly<TPageParam>>>): UseInfiniteQueryResult<TData, OperationError<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.paymentsService.getTransactionByIdApiV1PaymentsTransactionPaymentIdGet.useInfiniteQuery({
         *     path: {
         *         payment_id: paymentId
         *     },
         *     cookie: {
         *         access_token: accessToken
         *     }
         * }, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, TQueryFnData = GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TData = OperationInfiniteData<TQueryFnData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>>(parameters: ServiceOperationInfiniteQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters> | (DeepReadonly<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>), options: Omit<DefinedInitialDataInfiniteOptions<TQueryFnData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError, TData, ServiceOperationInfiniteQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, PartialParameters<DeepReadonly<TPageParam>>>): DefinedUseInfiniteQueryResult<TData, OperationError<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>>;
        /**
         * Monitors the number of queries currently fetching, matching the provided filters.
         * Useful for creating loading indicators or performing actions based on active requests.
         *
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsFetching|`useIsFetching(...)` documentation}
         * @example Checks the total number of queries fetching from the specified service method,
         * both normal and infinite. If no parameters are provided, no filtering is applied.
         * ```ts
         * const getTransactionByIdApiV1PaymentsTransactionPaymentIdGetTotal = qraft.paymentsService.getTransactionByIdApiV1PaymentsTransactionPaymentIdGet.useIsFetching()
         * ```
         * @example Checks the number of normal queries fetching with the specified parameters.
         * ```ts
         * const getTransactionByIdApiV1PaymentsTransactionPaymentIdGetByParametersTotal = qraft.paymentsService.getTransactionByIdApiV1PaymentsTransactionPaymentIdGet.useIsFetching({
         *     infinite: false,
         *     parameters: {
         *         path: {
         *             payment_id: paymentId
         *         },
         *         cookie: {
         *             access_token: accessToken
         *         }
         *     }
         * })
         * ```
         */
        useIsFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError> | QueryFiltersByQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>): number;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently. This is especially useful for managing complex data dependencies in parallel.
         *
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQueries|`useQueries(...)` documentation}
         * @example Multiple queries. Returns `data`, `error`, `isSuccess` and other properties.
         * ```ts
         * const getTransactionByIdApiV1PaymentsTransactionPaymentIdGetResults = qraft.paymentsService.getTransactionByIdApiV1PaymentsTransactionPaymentIdGet.useQueries({
         *     queries: [
         *         {
         *             path: {
         *                 payment_id: paymentId1
         *             },
         *             cookie: {
         *                 access_token: accessToken1
         *             }
         *         },
         *         {
         *             path: {
         *                 payment_id: paymentId2
         *             },
         *             cookie: {
         *                 access_token: accessToken2
         *             }
         *         }
         *     ]
         * });
         * getTransactionByIdApiV1PaymentsTransactionPaymentIdGetResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example Combined results. Only the data will be returned.
         * ```ts
         * const getTransactionByIdApiV1PaymentsTransactionPaymentIdGetCombinedResults = qraft.paymentsService.getTransactionByIdApiV1PaymentsTransactionPaymentIdGet.useQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {
         *             path: {
         *                 payment_id: paymentId1
         *             },
         *             cookie: {
         *                 access_token: accessToken1
         *             }
         *         },
         *         {
         *             path: {
         *                 payment_id: paymentId2
         *             },
         *             cookie: {
         *                 access_token: accessToken2
         *             }
         *         }
         *     ]
         * });
         * getTransactionByIdApiV1PaymentsTransactionPaymentIdGetCombinedResults.forEach(data => console.log({ data }));
         * ```
         */
        useQueries<T extends Array<UseQueryOptionsForUseQueries<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>>, TCombinedResult = Array<UseQueryResult<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>>>(options: {
            queries: T;
            combine?: (results: Array<UseQueryResult<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * Performs asynchronous data fetching with Suspense support.
         * Similar to useQuery but integrates with React Suspense for loading states.
         *
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQuery|`useSuspenseQuery(...)` documentation}
         * @example Suspense Query with parameters
         * ```ts
         * const data = qraft.paymentsService.getTransactionByIdApiV1PaymentsTransactionPaymentIdGet.useSuspenseQuery({
         *     path: {
         *         payment_id: paymentId
         *     },
         *     cookie: {
         *         access_token: accessToken
         *     }
         * })
         * ```
         */
        useSuspenseQuery<TData = GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData>(parameters: ServiceOperationQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters> | (DeepReadonly<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>), options?: Omit<UseSuspenseQueryOptions<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError, TData, ServiceOperationQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>>, "queryKey">): UseSuspenseQueryResult<TData, OperationError<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         * It functions similarly to `useInfiniteQuery`, but with added support for React Suspense.
         *
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseInfiniteQuery|`useSuspenseInfiniteQuery(...)` documentation}
         *
         * @example Suspense Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.paymentsService.getTransactionByIdApiV1PaymentsTransactionPaymentIdGet.useSuspenseInfiniteQuery({
         *     path: {
         *         payment_id: paymentId
         *     },
         *     cookie: {
         *         access_token: accessToken
         *     }
         * }, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useSuspenseInfiniteQuery<TPageParam extends GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, TData = GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData>(parameters: ServiceOperationInfiniteQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters> | (DeepReadonly<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>), options: Omit<UseSuspenseInfiniteQueryOptions<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError, OperationInfiniteData<TData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>, ServiceOperationInfiniteQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, PartialParameters<DeepReadonly<TPageParam>>>): UseSuspenseInfiniteQueryResult<OperationInfiniteData<TData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>, OperationError<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>>;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently with Suspense support.
         * Similar to useQueries but integrates with React Suspense for loading states.
         *
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQueries|`useSuspenseQueries(...)` documentation}
         * @example Basic usage with Suspense
         * ```ts
         * const getTransactionByIdApiV1PaymentsTransactionPaymentIdGetData = qraft.paymentsService.getTransactionByIdApiV1PaymentsTransactionPaymentIdGet.useSuspenseQueries({
         *     queries: [
         *         {
         *             path: {
         *                 payment_id: paymentId1
         *             },
         *             cookie: {
         *                 access_token: accessToken1
         *             }
         *         },
         *         {
         *             path: {
         *                 payment_id: paymentId2
         *             },
         *             cookie: {
         *                 access_token: accessToken2
         *             }
         *         }
         *     ]
         * });
         * getTransactionByIdApiV1PaymentsTransactionPaymentIdGetResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example With data transformation using combine
         * ```ts
         * const getTransactionByIdApiV1PaymentsTransactionPaymentIdGetCombinedData = qraft.paymentsService.getTransactionByIdApiV1PaymentsTransactionPaymentIdGet.useSuspenseQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {
         *             path: {
         *                 payment_id: paymentId1
         *             },
         *             cookie: {
         *                 access_token: accessToken1
         *             }
         *         },
         *         {
         *             path: {
         *                 payment_id: paymentId2
         *             },
         *             cookie: {
         *                 access_token: accessToken2
         *             }
         *         }
         *     ]
         * });
         * getTransactionByIdApiV1PaymentsTransactionPaymentIdGetCombinedData.forEach(data => console.log({ data }));
         * ```
         */
        useSuspenseQueries<T extends Array<UseQueryOptionsForUseSuspenseQuery<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>>, TCombinedResult = Array<UseSuspenseQueryResult<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>>>(options: {
            queries: T;
            combine?: (results: Array<WithOptional<UseSuspenseQueryResult<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>, "data">>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        fetchQuery(options: ServiceOperationFetchQueryOptions<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>): Promise<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData>;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        prefetchQuery(options: ServiceOperationFetchQueryOptions<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>): Promise<void>;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        ensureQueryData(options: ServiceOperationEnsureQueryDataOptions<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>): Promise<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData>;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        fetchInfiniteQuery<TPageParam extends GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>(options: ServiceOperationFetchInfiniteQueryOptions<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, DeepReadonly<TPageParam>, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>): Promise<OperationInfiniteData<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>>;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        prefetchInfiniteQuery<TPageParam extends GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>(options: ServiceOperationFetchInfiniteQueryOptions<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, DeepReadonly<TPageParam>, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>): Promise<void>;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        ensureInfiniteQueryData<TPageParam extends GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>(options: ServiceOperationEnsureInfiniteQueryDataOptions<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, DeepReadonly<TPageParam>, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>): Promise<OperationInfiniteData<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>>;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        getQueryData(parameters: ServiceOperationQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters> | (DeepReadonly<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>)): GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData | undefined;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        getInfiniteQueryData(parameters: ServiceOperationInfiniteQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters> | (DeepReadonly<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>)): OperationInfiniteData<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters> | undefined;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        getQueriesData<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError> | QueryFiltersByQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>): TInfinite extends true ? Array<[
            queryKey: ServiceOperationInfiniteQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>,
            data: NoInfer<OperationInfiniteData<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>> | undefined
        ]> : Array<[
            queryKey: ServiceOperationQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>,
            data: GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData | undefined
        ]>;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        getQueryState(parameters: ServiceOperationQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters> | (DeepReadonly<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>)): QueryState<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError> | undefined;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        getInfiniteQueryState(parameters: DeepReadonly<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters> | ServiceOperationInfiniteQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>): QueryState<OperationInfiniteData<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError> | undefined;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        setQueryData(parameters: (DeepReadonly<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>) | ServiceOperationQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>, updater: Updater<NoInfer<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData> | undefined, NoInfer<DeepReadonly<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData>> | undefined>, options?: SetDataOptions): GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData | undefined;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        setInfiniteQueryData(parameters: (DeepReadonly<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>) | ServiceOperationInfiniteQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>, updater: Updater<NoInfer<OperationInfiniteData<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>> | undefined, NoInfer<DeepReadonly<OperationInfiniteData<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters>>> | undefined>, options?: SetDataOptions): OperationInfiniteData<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters> | undefined;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        setQueriesData<TInfinite extends boolean = false>(filters: QueryFiltersByParameters<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError> | QueryFiltersByQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>, updater: Updater<NoInfer<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData> | undefined, NoInfer<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData> | undefined>, options?: SetDataOptions): Array<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData | undefined>;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        invalidateQueries<TInfinite extends boolean = false>(filters?: InvalidateQueryFilters<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>, options?: InvalidateOptions): Promise<void>;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        refetchQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError> | QueryFiltersByQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>, options?: RefetchOptions): Promise<void>;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        cancelQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError> | QueryFiltersByQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>, options?: CancelOptions): Promise<void>;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        removeQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError> | QueryFiltersByQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>): void;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        resetQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError> | QueryFiltersByQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>, options?: ResetOptions): Promise<void>;
        /**
         * @summary Get Transaction By Id
         * @description Get a transaction by id.
         */
        isFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError> | QueryFiltersByQueryKey<GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData, TInfinite, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters, GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError>): number;
        schema: GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema;
        types: {
            parameters: GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters;
            data: GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData;
            error: GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError;
        };
    };
    /**
     * @summary Get Transactions By User Id
     * @description Get a list of transactions by user id.
     */
    getTransactionsByUserIdApiV1PaymentsTransactionsGet: {
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: QueryFnOptionsByQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, TMeta, TSignal> | (QueryFnOptionsByParameters<GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, TMeta, TSignal> | void), client?: (schema: GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, options: {
            parameters: GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters;
            signal?: TSignal;
            meta?: TMeta;
        }) => Promise<RequestFnResponse<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>>): Promise<RequestFnResponse<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>>;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        getQueryKey(parameters: DeepReadonly<GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | void): ServiceOperationQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.paymentsService.getTransactionsByUserIdApiV1PaymentsTransactionsGet.useQuery()
         * ```
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.paymentsService.getTransactionsByUserIdApiV1PaymentsTransactionsGet.useQuery({
         *     cookie: {
         *         access_token: accessToken
         *     }
         * })
         * ```
         */
        useQuery<TData = GetTransactionsByUserIdApiV1PaymentsTransactionsGetData>(parameters: ServiceOperationQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | (DeepReadonly<GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | void), options?: Omit<UndefinedInitialDataOptions<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError, TData, ServiceOperationQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>>, "queryKey">): UseQueryResult<TData, OperationError<GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.paymentsService.getTransactionsByUserIdApiV1PaymentsTransactionsGet.useQuery()
         * ```
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.paymentsService.getTransactionsByUserIdApiV1PaymentsTransactionsGet.useQuery({
         *     cookie: {
         *         access_token: accessToken
         *     }
         * })
         * ```
         */
        useQuery<TData = GetTransactionsByUserIdApiV1PaymentsTransactionsGetData>(parameters: ServiceOperationQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | (DeepReadonly<GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | void), options: Omit<DefinedInitialDataOptions<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError, TData, ServiceOperationQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>>, "queryKey">): DefinedUseQueryResult<TData, OperationError<GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>>;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        getInfiniteQueryKey(parameters: DeepReadonly<GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | void): ServiceOperationInfiniteQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.paymentsService.getTransactionsByUserIdApiV1PaymentsTransactionsGet.useInfiniteQuery({
         *     cookie: {
         *         access_token: accessToken
         *     }
         * }, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, TQueryFnData = GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TData = OperationInfiniteData<TQueryFnData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>>(parameters: ServiceOperationInfiniteQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | (DeepReadonly<GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | void), options: Omit<UndefinedInitialDataInfiniteOptions<TQueryFnData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError, TData, ServiceOperationInfiniteQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<TQueryFnData, PartialParameters<DeepReadonly<TPageParam>>>): UseInfiniteQueryResult<TData, OperationError<GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.paymentsService.getTransactionsByUserIdApiV1PaymentsTransactionsGet.useInfiniteQuery({
         *     cookie: {
         *         access_token: accessToken
         *     }
         * }, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, TQueryFnData = GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TData = OperationInfiniteData<TQueryFnData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>>(parameters: ServiceOperationInfiniteQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | (DeepReadonly<GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | void), options: Omit<DefinedInitialDataInfiniteOptions<TQueryFnData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError, TData, ServiceOperationInfiniteQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, PartialParameters<DeepReadonly<TPageParam>>>): DefinedUseInfiniteQueryResult<TData, OperationError<GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>>;
        /**
         * Monitors the number of queries currently fetching, matching the provided filters.
         * Useful for creating loading indicators or performing actions based on active requests.
         *
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsFetching|`useIsFetching(...)` documentation}
         * @example Checks the total number of queries fetching from the specified service method,
         * both normal and infinite. If no parameters are provided, no filtering is applied.
         * ```ts
         * const getTransactionsByUserIdApiV1PaymentsTransactionsGetTotal = qraft.paymentsService.getTransactionsByUserIdApiV1PaymentsTransactionsGet.useIsFetching()
         * ```
         * @example Checks the number of normal queries fetching with the specified parameters.
         * ```ts
         * const getTransactionsByUserIdApiV1PaymentsTransactionsGetByParametersTotal = qraft.paymentsService.getTransactionsByUserIdApiV1PaymentsTransactionsGet.useIsFetching({
         *     infinite: false,
         *     parameters: {
         *         cookie: {
         *             access_token: accessToken
         *         }
         *     }
         * })
         * ```
         */
        useIsFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | QueryFiltersByQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>): number;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently. This is especially useful for managing complex data dependencies in parallel.
         *
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQueries|`useQueries(...)` documentation}
         * @example Multiple queries. Returns `data`, `error`, `isSuccess` and other properties.
         * ```ts
         * const getTransactionsByUserIdApiV1PaymentsTransactionsGetResults = qraft.paymentsService.getTransactionsByUserIdApiV1PaymentsTransactionsGet.useQueries({
         *     queries: [
         *         {
         *             cookie: {
         *                 access_token: accessToken1
         *             }
         *         },
         *         {
         *             cookie: {
         *                 access_token: accessToken2
         *             }
         *         }
         *     ]
         * });
         * getTransactionsByUserIdApiV1PaymentsTransactionsGetResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example Combined results. Only the data will be returned.
         * ```ts
         * const getTransactionsByUserIdApiV1PaymentsTransactionsGetCombinedResults = qraft.paymentsService.getTransactionsByUserIdApiV1PaymentsTransactionsGet.useQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {
         *             cookie: {
         *                 access_token: accessToken1
         *             }
         *         },
         *         {
         *             cookie: {
         *                 access_token: accessToken2
         *             }
         *         }
         *     ]
         * });
         * getTransactionsByUserIdApiV1PaymentsTransactionsGetCombinedResults.forEach(data => console.log({ data }));
         * ```
         */
        useQueries<T extends Array<UseQueryOptionsForUseQueries<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>>, TCombinedResult = Array<UseQueryResult<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>>>(options: {
            queries: T;
            combine?: (results: Array<UseQueryResult<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * Performs asynchronous data fetching with Suspense support.
         * Similar to useQuery but integrates with React Suspense for loading states.
         *
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQuery|`useSuspenseQuery(...)` documentation}
         * @example Suspense Query without parameters
         * ```ts
         * const data = qraft.paymentsService.getTransactionsByUserIdApiV1PaymentsTransactionsGet.useSuspenseQuery()
         * ```
         * @example Suspense Query with parameters
         * ```ts
         * const data = qraft.paymentsService.getTransactionsByUserIdApiV1PaymentsTransactionsGet.useSuspenseQuery({
         *     cookie: {
         *         access_token: accessToken
         *     }
         * })
         * ```
         */
        useSuspenseQuery<TData = GetTransactionsByUserIdApiV1PaymentsTransactionsGetData>(parameters: ServiceOperationQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | (DeepReadonly<GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | void), options?: Omit<UseSuspenseQueryOptions<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError, TData, ServiceOperationQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>>, "queryKey">): UseSuspenseQueryResult<TData, OperationError<GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         * It functions similarly to `useInfiniteQuery`, but with added support for React Suspense.
         *
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseInfiniteQuery|`useSuspenseInfiniteQuery(...)` documentation}
         *
         * @example Suspense Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.paymentsService.getTransactionsByUserIdApiV1PaymentsTransactionsGet.useSuspenseInfiniteQuery({
         *     cookie: {
         *         access_token: accessToken
         *     }
         * }, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useSuspenseInfiniteQuery<TPageParam extends GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, TData = GetTransactionsByUserIdApiV1PaymentsTransactionsGetData>(parameters: ServiceOperationInfiniteQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | (DeepReadonly<GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | void), options: Omit<UseSuspenseInfiniteQueryOptions<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError, OperationInfiniteData<TData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>, ServiceOperationInfiniteQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, PartialParameters<DeepReadonly<TPageParam>>>): UseSuspenseInfiniteQueryResult<OperationInfiniteData<TData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>, OperationError<GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>>;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently with Suspense support.
         * Similar to useQueries but integrates with React Suspense for loading states.
         *
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQueries|`useSuspenseQueries(...)` documentation}
         * @example Basic usage with Suspense
         * ```ts
         * const getTransactionsByUserIdApiV1PaymentsTransactionsGetData = qraft.paymentsService.getTransactionsByUserIdApiV1PaymentsTransactionsGet.useSuspenseQueries({
         *     queries: [
         *         {
         *             cookie: {
         *                 access_token: accessToken1
         *             }
         *         },
         *         {
         *             cookie: {
         *                 access_token: accessToken2
         *             }
         *         }
         *     ]
         * });
         * getTransactionsByUserIdApiV1PaymentsTransactionsGetResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example With data transformation using combine
         * ```ts
         * const getTransactionsByUserIdApiV1PaymentsTransactionsGetCombinedData = qraft.paymentsService.getTransactionsByUserIdApiV1PaymentsTransactionsGet.useSuspenseQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {
         *             cookie: {
         *                 access_token: accessToken1
         *             }
         *         },
         *         {
         *             cookie: {
         *                 access_token: accessToken2
         *             }
         *         }
         *     ]
         * });
         * getTransactionsByUserIdApiV1PaymentsTransactionsGetCombinedData.forEach(data => console.log({ data }));
         * ```
         */
        useSuspenseQueries<T extends Array<UseQueryOptionsForUseSuspenseQuery<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>>, TCombinedResult = Array<UseSuspenseQueryResult<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>>>(options: {
            queries: T;
            combine?: (results: Array<WithOptional<UseSuspenseQueryResult<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>, "data">>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        fetchQuery(options: ServiceOperationFetchQueryOptions<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | void): Promise<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData>;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        prefetchQuery(options: ServiceOperationFetchQueryOptions<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | void): Promise<void>;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        ensureQueryData(options: ServiceOperationEnsureQueryDataOptions<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | void): Promise<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData>;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        fetchInfiniteQuery<TPageParam extends GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>(options: ServiceOperationFetchInfiniteQueryOptions<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, DeepReadonly<TPageParam>, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | void): Promise<OperationInfiniteData<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>>;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        prefetchInfiniteQuery<TPageParam extends GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>(options: ServiceOperationFetchInfiniteQueryOptions<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, DeepReadonly<TPageParam>, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | void): Promise<void>;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        ensureInfiniteQueryData<TPageParam extends GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>(options: ServiceOperationEnsureInfiniteQueryDataOptions<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, DeepReadonly<TPageParam>, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | void): Promise<OperationInfiniteData<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>>;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        getQueryData(parameters: ServiceOperationQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | (DeepReadonly<GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | void)): GetTransactionsByUserIdApiV1PaymentsTransactionsGetData | undefined;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        getInfiniteQueryData(parameters: ServiceOperationInfiniteQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | (DeepReadonly<GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | void)): OperationInfiniteData<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | undefined;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        getQueriesData<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | QueryFiltersByQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>): TInfinite extends true ? Array<[
            queryKey: ServiceOperationInfiniteQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>,
            data: NoInfer<OperationInfiniteData<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>> | undefined
        ]> : Array<[
            queryKey: ServiceOperationQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>,
            data: GetTransactionsByUserIdApiV1PaymentsTransactionsGetData | undefined
        ]>;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        getQueryState(parameters: ServiceOperationQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | (DeepReadonly<GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | void)): QueryState<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | undefined;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        getInfiniteQueryState(parameters: DeepReadonly<GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | ServiceOperationInfiniteQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | void): QueryState<OperationInfiniteData<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | undefined;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        setQueryData(parameters: (DeepReadonly<GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | undefined) | ServiceOperationQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>, updater: Updater<NoInfer<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData> | undefined, NoInfer<DeepReadonly<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData>> | undefined>, options?: SetDataOptions): GetTransactionsByUserIdApiV1PaymentsTransactionsGetData | undefined;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        setInfiniteQueryData(parameters: (DeepReadonly<GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | undefined) | ServiceOperationInfiniteQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>, updater: Updater<NoInfer<OperationInfiniteData<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>> | undefined, NoInfer<DeepReadonly<OperationInfiniteData<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters>>> | undefined>, options?: SetDataOptions): OperationInfiniteData<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters> | undefined;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        setQueriesData<TInfinite extends boolean = false>(filters: QueryFiltersByParameters<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | QueryFiltersByQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>, updater: Updater<NoInfer<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData> | undefined, NoInfer<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData> | undefined>, options?: SetDataOptions): Array<GetTransactionsByUserIdApiV1PaymentsTransactionsGetData | undefined>;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        invalidateQueries<TInfinite extends boolean = false>(filters?: InvalidateQueryFilters<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>, options?: InvalidateOptions): Promise<void>;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        refetchQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | QueryFiltersByQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>, options?: RefetchOptions): Promise<void>;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        cancelQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | QueryFiltersByQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>, options?: CancelOptions): Promise<void>;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        removeQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | QueryFiltersByQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>): void;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        resetQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | QueryFiltersByQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>, options?: ResetOptions): Promise<void>;
        /**
         * @summary Get Transactions By User Id
         * @description Get a list of transactions by user id.
         */
        isFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError> | QueryFiltersByQueryKey<GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema, GetTransactionsByUserIdApiV1PaymentsTransactionsGetData, TInfinite, GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters, GetTransactionsByUserIdApiV1PaymentsTransactionsGetError>): number;
        schema: GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema;
        types: {
            parameters: GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters;
            data: GetTransactionsByUserIdApiV1PaymentsTransactionsGetData;
            error: GetTransactionsByUserIdApiV1PaymentsTransactionsGetError;
        };
    };
}
/**
 * @summary Create Checkout Session
 * @description Create a checkout session.
 */
export const createCheckoutSessionApiV1PaymentsCheckoutPost = {
    schema: {
        method: "post",
        url: "/api/v1/payments/checkout",
        mediaType: ["application/json"]
    }
} as {
    schema: CreateCheckoutSessionApiV1PaymentsCheckoutPostSchema;
    [QraftServiceOperationsToken]: PaymentsService["createCheckoutSessionApiV1PaymentsCheckoutPost"];
};
/**
 * @summary Get Transaction By Id
 * @description Get a transaction by id.
 */
export const getTransactionByIdApiV1PaymentsTransactionPaymentIdGet = {
    schema: {
        method: "get",
        url: "/api/v1/payments/transaction/{payment_id}"
    }
} as {
    schema: GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema;
    [QraftServiceOperationsToken]: PaymentsService["getTransactionByIdApiV1PaymentsTransactionPaymentIdGet"];
};
/**
 * @summary Get Transactions By User Id
 * @description Get a list of transactions by user id.
 */
export const getTransactionsByUserIdApiV1PaymentsTransactionsGet = {
    schema: {
        method: "get",
        url: "/api/v1/payments/transactions"
    }
} as {
    schema: GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema;
    [QraftServiceOperationsToken]: PaymentsService["getTransactionsByUserIdApiV1PaymentsTransactionsGet"];
};
export const paymentsService = {
    createCheckoutSessionApiV1PaymentsCheckoutPost,
    getTransactionByIdApiV1PaymentsTransactionPaymentIdGet,
    getTransactionsByUserIdApiV1PaymentsTransactionsGet
} as const;
type CreateCheckoutSessionApiV1PaymentsCheckoutPostSchema = {
    method: "post";
    url: "/api/v1/payments/checkout";
    mediaType: [
        "application/json"
    ];
};
type CreateCheckoutSessionApiV1PaymentsCheckoutPostParameters = paths["/api/v1/payments/checkout"]["post"]["parameters"];
type CreateCheckoutSessionApiV1PaymentsCheckoutPostData = paths["/api/v1/payments/checkout"]["post"]["responses"]["200"]["content"]["application/json"];
type CreateCheckoutSessionApiV1PaymentsCheckoutPostError = paths["/api/v1/payments/checkout"]["post"]["responses"]["422"]["content"]["application/json"] | null;
type CreateCheckoutSessionApiV1PaymentsCheckoutPostBody = paths["/api/v1/payments/checkout"]["post"]["requestBody"]["content"]["application/json"];
type GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetSchema = {
    method: "get";
    url: "/api/v1/payments/transaction/{payment_id}";
};
type GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetParameters = paths["/api/v1/payments/transaction/{payment_id}"]["get"]["parameters"];
type GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetData = paths["/api/v1/payments/transaction/{payment_id}"]["get"]["responses"]["200"]["content"]["application/json"];
type GetTransactionByIdApiV1PaymentsTransactionPaymentIdGetError = paths["/api/v1/payments/transaction/{payment_id}"]["get"]["responses"]["422"]["content"]["application/json"] | null;
type GetTransactionsByUserIdApiV1PaymentsTransactionsGetSchema = {
    method: "get";
    url: "/api/v1/payments/transactions";
};
type GetTransactionsByUserIdApiV1PaymentsTransactionsGetParameters = paths["/api/v1/payments/transactions"]["get"]["parameters"];
type GetTransactionsByUserIdApiV1PaymentsTransactionsGetData = paths["/api/v1/payments/transactions"]["get"]["responses"]["200"]["content"]["application/json"];
type GetTransactionsByUserIdApiV1PaymentsTransactionsGetError = paths["/api/v1/payments/transactions"]["get"]["responses"]["422"]["content"]["application/json"] | null;
