"""fix type jti

Revision ID: 0e9c3d89ccd1
Revises: cc518bc11688
Create Date: 2025-11-23 23:03:11.068734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e9c3d89ccd1"
down_revision: Union[str, Sequence[str], None] = "cc518bc11688"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "blacklist_tokens",
        "jti",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "blacklist_tokens",
        "jti",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=36),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
