"""fix add created_at payment system

Revision ID: 16b639bf35e3
Revises: a27f3fe2c524
Create Date: 2025-11-22 18:55:12.277904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16b639bf35e3"
down_revision: Union[str, Sequence[str], None] = "a27f3fe2c524"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    with op.batch_alter_table("transactions") as batch:
        batch.alter_column("created_at", nullable=False, existing_type=sa.DateTime())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("'2025-11-22 18:54:50'"),
    )
    # ### end Alembic commands ###
