"""add like/dislike

Revision ID: 1a6da54da612
Revises: 9637257deaf6
Create Date: 2025-11-16 20:13:29.835882

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a6da54da612"
down_revision: Union[str, Sequence[str], None] = "9637257deaf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "styles", sa.Column("description", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("styles", "description")
    # ### end Alembic commands ###
