"""add payment system

Revision ID: 32d95ba52cac
Revises: 5989c96e0988
Create Date: 2025-11-22 17:53:10.025265

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32d95ba52cac"
down_revision: Union[str, Sequence[str], None] = "5989c96e0988"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("payment_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "payment_id")
    # ### end Alembic commands ###
