"""message

Revision ID: 7eca35ff1e00
Revises: f1e25c850f4f
Create Date: 2025-11-15 13:23:47.786106

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7eca35ff1e00'
down_revision: Union[str, Sequence[str], None] = 'f1e25c850f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_images', 'description')
    # ### end Alembic commands ###
