"""add like/dislike

Revision ID: 9637257deaf6
Revises: addf5a52590e
Create Date: 2025-11-16 01:04:05.727044

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9637257deaf6'
down_revision: Union[str, Sequence[str], None] = 'addf5a52590e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('liked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_images', 'liked')
    # ### end Alembic commands ###
