"""add created_at payment system

Revision ID: a27f3fe2c524
Revises: 32d95ba52cac
Create Date: 2025-11-22 18:54:50.830073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a27f3fe2c524"
down_revision: Union[str, Sequence[str], None] = "32d95ba52cac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default="2025-11-22 18:54:50",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "created_at")
    # ### end Alembic commands ###
