"""add sideviews

Revision ID: addf5a52590e
Revises: 7eca35ff1e00
Create Date: 2025-11-15 13:46:28.835118

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'addf5a52590e'
down_revision: Union[str, Sequence[str], None] = '7eca35ff1e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('right_view_url', sa.String(), nullable=True))
    op.add_column('generated_images', sa.Column('left_view_url', sa.String(), nullable=True))
    op.add_column('generated_images', sa.Column('back_view_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_images', 'back_view_url')
    op.drop_column('generated_images', 'left_view_url')
    op.drop_column('generated_images', 'right_view_url')
    # ### end Alembic commands ###
