"""init

Revision ID: cc518bc11688
Revises:
Create Date: 2025-11-23 14:58:54.723234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc518bc11688"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklist_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("jti", sa.String(length=36), nullable=False),
        sa.Column(
            "token_type",
            sa.Enum(
                "ACCESS",
                "PASSWORD_RESET",
                "SIGNUP_VERIFY",
                "LOGIN_VERIFY",
                "REFRESH",
                name="tokentype",
            ),
            nullable=False,
        ),
        sa.Column("blacklisted_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
    )
    op.create_table(
        "styles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("prompt", sa.String(length=2000), nullable=False),
        sa.Column(
            "category",
            sa.Enum("standard", "celebrity", name="stylecategory"),
            nullable=False,
        ),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=100), server_default="unknown", nullable=True
        ),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column("userpic", sa.String(), nullable=True),
        sa.Column("verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("credits", sa.Integer(), server_default="3", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "generated_images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("style_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("output_image_url", sa.String(), nullable=True),
        sa.Column("input_image_url", sa.String(), nullable=False),
        sa.Column("right_view_url", sa.String(), nullable=True),
        sa.Column("left_view_url", sa.String(), nullable=True),
        sa.Column("back_view_url", sa.String(), nullable=True),
        sa.Column("liked", sa.Boolean(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="imagestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("time_taken", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["style_id"],
            ["styles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("payment_id", sa.String(), nullable=True),
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                "PROCESSING",
                "REQUIRES_CUSTOMER_ACTION",
                "REQUIRES_MERCHANT_ACTION",
                "REQUIRES_PAYMENT_METHOD",
                "REQUIRES_CONFIRMATION",
                "REQUIRES_CAPTURE",
                "PARTIALLY_CAPTURED",
                "PARTIALLY_CAPTURED_AND_CAPTURABLE",
                name="intentstatus",
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("credits_added", sa.Integer(), nullable=True),
        sa.Column("webhook_id", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("generated_images")
    op.drop_table("users")
    op.drop_table("styles")
    op.drop_table("blacklist_tokens")
    # ### end Alembic commands ###
