"""remove email code verification

Revision ID: da0d611d2250
Revises: e3adc2bd52dc
Create Date: 2025-11-18 20:14:36.104675

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da0d611d2250"
down_revision: Union[str, Sequence[str], None] = "e3adc2bd52dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verification_codes_id"), table_name="verification_codes")
    op.drop_table("verification_codes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_codes",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("code", sa.VARCHAR(), nullable=False),
        sa.Column("expires_at", sa.DATETIME(), nullable=False),
        sa.Column("used", sa.BOOLEAN(), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_codes_id"), "verification_codes", ["id"], unique=False
    )
    # ### end Alembic commands ###
