"""change in lol

Revision ID: f1e25c850f4f
Revises: fdff5923b8de
Create Date: 2025-11-08 20:18:19.206797

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1e25c850f4f"
down_revision: Union[str, Sequence[str], None] = "fdff5923b8de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generated_images", sa.Column("time_taken", sa.Float(), nullable=True)
    )
    op.drop_column("generated_images", "prediction_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generated_images", sa.Column("prediction_id", sa.VARCHAR(), nullable=True)
    )
    op.drop_column("generated_images", "time_taken")
    # ### end Alembic commands ###
